# resource
total_cores_overweight_percent: 1  # 1 means no overweight
total_memory_overweight_percent: 1  # 1 means no overweight
task_parallelism: 1
task_cores: 4
task_memory: 0  # mb
max_cores_percent_per_job: 1  # 1 means total

# scheduling
job_timeout: 259200 # s
remote_request_timeout: 30000  # ms
federated_command_trys: 3
end_status_job_scheduling_time_limit: 300000 # ms
end_status_job_scheduling_updates: 1
auto_retries: 0
auto_retry_delay: 1  #seconds
# It can also be specified in the job configuration using the federated_status_collect_type parameter
federated_status_collect_type: PUSH
detect_connect_max_retry_count: 3
detect_connect_long_retry_count: 2

# upload
upload_block_max_bytes: 104857600 # bytes

#component output
output_data_summary_count_limit: 100

task_default_conf:
  input:
    artifacts:
      model_get_uri: /v2/worker/task/report
  output:
    model:
      type: directory
      metadata:
        uri: /worker/task/model/task_name/model_id/model_version
        format: json
    metric:
      type: directory
      metadata:
        uri: xxx
        format: json
    data:
      type: directory
      metadata:
        uri: xxx
        format: csv
  logger:
    type: flow
    metadata:
      level: DEBUG
      debug_mode: true
  device:
    type: CPU
  mlmd:
    type: flow
    metadata:
      statu_uri: /worker/task/report
      tracking_uri: /worker/task/output/tracking
